# Copyright (C) 2026 ETH Zurich, Institute for Particle Physics and Astrophysics

"""
Created September 2026
Author: Arne Thomsen (with Claude)

Exports draws from the analysis prior, for the prior band on the paper_2 posterior figures.

The band is not a box, which is the whole reason it has to come from here: the analysis prior is
the CosmoGrid convex hull in the Om-sigma_8 plane plus the w phantom-crossing threshold, so its
boundary is a msfm object and cannot be reconstructed from a range per parameter. The draws are
generated by prior.generate_randoms and rejected against that hull, so the export writes the
survivors.

The prior is read from a *run's own configs.yaml*, not from a repo config: the band has to be the
prior the networks were actually trained under, and a restored run reads its own snapshot. Point
--run_config at the run the figure names as its reference; paper_2_plotting prints the exact
command, with both paths filled in, when the file it wants is not there.

Cheap: a few seconds of rejection sampling and a ~30 MB h5, no maps. A login node is fine.

    ~/dlss/torch_env/bin/python3 dev/scripts/figures/export_prior_draws.py \
        --run_config <store>/runs/v17/baseline/maps/combined/<run>/configs.yaml \
        --version v17
"""

import argparse
import os
import subprocess

import h5py
import numpy as np
import yaml

from msfm.utils import prior

REPO_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "../../.."))

#: Matches the seed the figures were first drawn with. generate_randoms does not seed itself, and
#: the exported file is what pins the published band, so this has to be explicit.
SEED = 8


def parse_args():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--run_config", required=True, help="configs.yaml of the run whose prior this is")
    parser.add_argument("--version", required=True, help="forward-model version, for the output name (e.g. v17)")
    parser.add_argument("--params", nargs="+", default=["Om", "S8", "w0"], help="parameters to draw")
    parser.add_argument("--n_draws", type=int, default=2_000_000, help="draws attempted before rejection")
    parser.add_argument("--seed", type=int, default=SEED)
    parser.add_argument("--output", default=None, help="path of the .h5 to write; defaults to the plotting cache")
    return parser.parse_args()


def output_name(version, params, n_draws):
    """The filename dlss_plot.priors looks for. Keep the two in step -- it is the whole interface."""
    return f"prior_draws_{version}_{'-'.join(params)}_{n_draws}.h5"


def default_output(version, params, n_draws):
    return os.path.abspath(
        os.path.join(REPO_DIR, "../deep_lss_paper/paper_2_plotting/cache", output_name(version, params, n_draws))
    )


def git_hash(path):
    try:
        return subprocess.check_output(["git", "-C", path, "rev-parse", "HEAD"], text=True).strip()
    except Exception:
        return "unknown"


def main():
    args = parse_args()
    output = args.output or default_output(args.version, args.params, args.n_draws)

    print(f"reading {args.run_config}", flush=True)
    with open(args.run_config) as f:
        conf = yaml.safe_load(f)["msfm"]

    print(f"drawing {args.n_draws:,} {args.params} at seed {args.seed}", flush=True)
    np.random.seed(args.seed)
    samples = prior.generate_randoms(params=args.params, conf=conf, n_draws=args.n_draws, output_S8=True)
    print(f"{len(samples):,} inside the prior ({len(samples) / args.n_draws:.1%})", flush=True)

    # ------------------------------------------------------------------------------------ write
    os.makedirs(os.path.dirname(output), exist_ok=True)
    print(f"writing {output}", flush=True)

    with h5py.File(output, "w") as f:
        f.attrs["description"] = (
            "draws from the analysis prior -- the CosmoGrid convex hull in the Om-sigma_8 plane "
            "plus the w phantom-crossing threshold -- that survived rejection, for the prior band "
            "on the paper_2 posterior figures. Produced by "
            "msfm/dev/scripts/figures/export_prior_draws.py from the run config it names below"
        )
        f.attrs["run_config"] = os.path.abspath(args.run_config)
        f.attrs["version"] = args.version
        f.attrs["params"] = args.params
        f.attrs["n_draws"] = args.n_draws
        f.attrs["seed"] = args.seed
        f.attrs["msfm_git_sha"] = git_hash(REPO_DIR)

        f.create_dataset("samples", data=samples.astype(np.float64), compression="gzip", compression_opts=4)

    print("done", flush=True)


if __name__ == "__main__":
    main()
